version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: tvmotel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:supersecretpassword@postgres:5432/tvmotel?schema=public"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: "yoursecretjwtkeygoesherechangethisinproduction"
      PORT: 5050
      HOST: 0.0.0.0
    depends_on:
      - postgres
      - redis

  app-front:
    build:
      context: .
      dockerfile: apps/app-front/Dockerfile
    restart: always
    depends_on:
      - api

  admin-panel:
    build:
      context: .
      dockerfile: apps/admin-panel/Dockerfile
    restart: always
    depends_on:
      - api

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    restart: always
    expose:
      - "80"
    depends_on:
      - app-front
      - admin-panel
      - api

volumes:
  postgres_data:
  redis_data: